### PR TITLE
Fix crash on unknown COSEAlgorithmIdentifier in FIDO MDS

### LINKED ISSUE #387: FIDO metadata failure: Unknown COSE algorithm identifier: -37
It appears that the latest FIDO metadata feed has added a new algorithm that cannot be recognized by this library here. Relevant stack trace:

```
Caused by:
com.fasterxml.jackson.databind.exc.ValueInstantiationException: 
Cannot construct instance of `com.yubico.webauthn.data.COSEAlgorithmIdentifier`, problem: Unknown COSE algorithm identifier: -37
at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 220483] 
(through reference chain: com.yubico.fido.metadata.MetadataBLOBPayload$MetadataBLOBPayloadBuilder["entries"]->java.util.HashSet[23]->
com.yubico.fido.metadata.MetadataBLOBPayloadEntry$MetadataBLOBPayloadEntryBuilder["metadataStatement"]->
com.yubico.fido.metadata.MetadataStatement$MetadataStatementBuilder["authenticatorGetInfo"]->
com.yubico.fido.metadata.AuthenticatorGetInfo$AuthenticatorGetInfoBuilder["algorithms"]->java.util.ArrayList[1]->
com.yubico.webauthn.data.PublicKeyCredentialParameters["alg"])
```

### PR DESCRIPTION
**Pull request by emlun**
Fixes #387.

I chose to do it this way instead of adding a `COSEAlgorithmIdentifier` constant primarily because doing that would advertise support for verifying `PS256` signatures, which is not included in this change. This will also be more robust to future MDS entries adding more unknown algorithm values.

### CODE REVIEW

File: webauthn-server-attestation/src/main/java/com/yubico/fido/metadata/AuthenticatorGetInfo.java [hunk 1]
```diff
@@ -377,4 +380,44 @@ public void serialize(
...
+          p.readValueAs(PublicKeyCredentialParametersIgnoringUnknownValues[].class);
+      return Arrays.stream(pkcpiuvs)
+          .flatMap(
+              pkcpiuv -> {
+                if (pkcpiuv != null && pkcpiuv.value != null) {
+                  return Stream.of(pkcpiuv.value);
+                } else {
+                  return Stream.empty();
+                }
+              })
```
Comment (georgespalding) [inline webauthn-server-attestation/src/main/java/com/yubico/fido/metadata/AuthenticatorGetInfo.java:419]:
```suggestion
          .filter(Objects::nonNull)
          .filter(pkcpiuv -> pkcpiuv.value != null)
```
